import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Marko_One } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'
import MobileNavigation from '@/components/MobileNavigation/MobileNavigation'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter', display: 'swap' })

const marko = Marko_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-marko',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${marko.variable} ${inter.variable} min-h-screen`}>
        <Header />
        {children}
        <MobileNavigation />
        <Footer />
      </body>
    </html>
  )
}
